In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# Way.1

a_tensor = tf.constant([1,2,3,4])

In [3]:
a_tensor

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [5]:
zero_dimension = tf.constant(4)
zero_dimension

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [9]:
two_d = tf.constant( [[2,3,5],
                      [1,2,3]], dtype="float32")

In [10]:
two_d

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[2., 3., 5.],
       [1., 2., 3.]], dtype=float32)>

In [11]:
two_d.shape

TensorShape([2, 3])

In [17]:
three_d = tf.constant( [ [[1,2,3],[2,3,3]],
                         [[2,3,3],[3,4,3]] ] )

In [18]:
three_d.shape

TensorShape([2, 2, 3])

In [19]:
a_tensor.shape

TensorShape([4])

In [20]:
empty = tf.constant(3)

In [21]:
empty.shape

TensorShape([])

In [22]:
three_d

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 3, 3]],

       [[2, 3, 3],
        [3, 4, 3]]], dtype=int32)>

In [23]:
three_d[0]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 3]], dtype=int32)>

In [24]:
three_d[1]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 3],
       [3, 4, 3]], dtype=int32)>

In [25]:
three_d[:,0]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 3]], dtype=int32)>

In [26]:
three_d[:,1]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 3],
       [3, 4, 3]], dtype=int32)>

In [27]:
three_d[:,:,0]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3]], dtype=int32)>

In [28]:
three_d[:,:,1]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [3, 4]], dtype=int32)>

In [29]:
three_d[:,:,2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [3, 3]], dtype=int32)>

In [30]:
a = tf.constant([1,2,3,4])

In [31]:
a.numpy().reshape((2,2))

array([[1, 2],
       [3, 4]], dtype=int32)

In [32]:
a = tf.constant([1,2,3,4,3,4,5,5])
a.numpy().reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[3, 4],
        [5, 5]]], dtype=int32)

In [33]:
first = tf.constant([[2,3,4],
                    [1,2,3]])

In [34]:
second = tf.constant([[1,2,3,4],
                     [1,2,3,4],
                     [5,6,7,8]])

In [35]:
first @ second

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[25, 34, 43, 52],
       [18, 24, 30, 36]], dtype=int32)>

In [36]:
tf.matmul(first, second)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[25, 34, 43, 52],
       [18, 24, 30, 36]], dtype=int32)>

In [38]:
a = tf.constant([[1,2],
                [3,4]])
b = tf.constant([[1,2],
                [3,4]])

In [39]:
a * b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [40]:
second.numpy().T

array([[1, 1, 5],
       [2, 2, 6],
       [3, 3, 7],
       [4, 4, 8]], dtype=int32)

In [44]:
a1 = tf.constant([ [1,2,-3 ],[1,-2,4],[0,9,1]], dtype="float32")

In [45]:
a1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.,  2., -3.],
       [ 1., -2.,  4.],
       [ 0.,  9.,  1.]], dtype=float32)>

In [46]:
tf.linalg.det(a1)

<tf.Tensor: shape=(), dtype=float32, numpy=-67.000015>

In [47]:
tf.linalg.inv(a1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.56716424,  0.4328358 , -0.02985075],
       [ 0.01492537, -0.01492537,  0.10447761],
       [-0.13432835,  0.13432835,  0.05970149]], dtype=float32)>